---
# MySQL Secrets
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: wordpress
type: Opaque
data:
  mysql-root-password: dXNlcnBhc3N3b3Jk
  mysql-user: d29yZHByZXNz
  mysql-password: d29yZHByZXNzcGFzc3dvcmQ=