---
# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
  namespace: wordpress
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/mysql